### ISSUE TITLE
How to set the number of pictures displayed on each page？

### ISSUE THREAD

**Issue by fifteenbao** [klugjo/hexo-theme-magnetic#29]
How to set the number of pictures displayed on each page？
The homepage will show 10 pictures with two blank spaces.
eg: https://fifteenbao.com/

**Comment by fifteenbao** [comment]
Modify the root directory
```
index_generator:
  path: ''
  per_page: 16
  order_by: -date
```
